/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'surface-container-high': '#e7e8e9',
        'primary-fixed-dim': '#aac7ff',
        background: '#f8f9fa',
        'surface-bright': '#f8f9fa',
        'outline-variant': '#c3c6d2',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#001b3e',
        outline: '#737782',
        'inverse-on-surface': '#f0f1f2',
        tertiary: '#521e00',
        'on-background': '#191c1d',
        'on-error': '#ffffff',
        'on-surface': '#191c1d',
        'tertiary-fixed-dim': '#ffb692',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#aac7ff',
        'on-primary-fixed-variant': '#07458c',
        'inverse-surface': '#2e3132',
        'surface-container': '#edeeef',
        'secondary-container': '#e80f16',
        'tertiary-fixed': '#ffdbcb',
        error: '#ba1a1a',
        'surface-container-low': '#f3f4f5',
        'surface-dim': '#d9dadb',
        'primary-container': '#014389',
        primary: '#002d60',
        'on-secondary': '#ffffff',
        'on-primary-container': '#87b2ff',
        'tertiary-container': '#752f00',
        'surface-container-highest': '#e1e3e4',
        'secondary-fixed': '#ffdad5',
        'secondary-fixed-dim': '#ffb4aa',
        'on-tertiary-container': '#fe9863',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#793101',
        'on-secondary-fixed': '#410001',
        surface: '#f8f9fa',
        'on-surface-variant': '#424751',
        'on-tertiary-fixed': '#341100',
        'on-secondary-container': '#fffbff',
        'surface-variant': '#e1e3e4',
        'surface-tint': '#2d5ea5',
        'on-secondary-fixed-variant': '#930007',
        'primary-fixed': '#d6e3ff',
        secondary: '#bc000c',
      },
      borderRadius: {
        DEFAULT: '1.5rem',
        lg: '2.5rem',
        xl: '4rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Nunito', 'sans-serif'],
        body: ['Nunito', 'sans-serif'],
        label: ['Nunito', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
